version: '3.8'
services:
  backup-service:
    build: .
    container_name: backup-service
    restart: unless-stopped
    # env_file:
    #   - .env
    environment:
      TZ: Europe/Paris
      GPG_PASSWORD: changeme

      TELEGRAM_BOT_TOKEN: 
      TELEGRAM_CHAT_ID: 

      EMAIL_HOST: smtp.example.com
      EMAIL_PORT: 587
      EMAIL_USER: me@example.com
      EMAIL_PASS: secret
      EMAIL_TO: notify@example.com

      CRON_SCHEDULE: "30 1 * * *"
      MAX_BACKUPS: 4
    volumes:
      - /mnt/srv/docker:/data:ro
      - /mnt/srv/Mega:/backups
      - /mnt/srv/docker/logs/backup:/logs
