version: '3.8'

services:
  backup-service:
    image: ghcr.io/sen-se1/docker-backup-bot:latest
    container_name: backup-service
    restart: unless-stopped
    depends_on:
      - rclone
    # env_file:
    #   - .env
    environment:
      TZ: Europe/Paris
      GPG_PASSWORD: changeme

      ENABLE_RCLONE_WAIT: true  # 👈 Enable upload wait check (now support only mega) "Default value is false"
      RCLONE_USER: user
      RCLONE_PASS: rclone
      RCLONE_HOST: rclone:5572
      RCLONE_REMOTE_FOLDER: shs-backup

      TELEGRAM_BOT_TOKEN: your_token
      TELEGRAM_CHAT_ID: your_chat_id

      SMTP_HOST: smtp.example.com
      SMTP_PORT: 587
      SMTP_USER: me@example.com
      SMTP_PASS: secret
      EMAIL_FROM: backupbot@yourdomain.com
      EMAIL_TO: notify@example.com

      CRON_SCHEDULE: "30 1 * * *"
      MAX_BACKUPS: 4
    volumes:
      - /mnt/srv/docker:/data:ro
      - /mnt/srv/Mega:/backups
      - /mnt/srv/docker/logs/backup:/logs
